#
# ESPHome HomeAssistant Interface Panel
# https://github.com/f18m/esphome-ha-interface-panel
#
#
# This is the main configuration file for ESPHome. 
# It uses the package system to include code from the "esphome-modular-lvgl-buttons" repository.
#

# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  icon_font_small: mdi_icons_20
  text_font: nunito_20

  # text_color: white
  # bg_color: black
  # button_on_color: "ep_orange"
  # button_off_color: "darkgray"
  # icon_on_color: "yellow"
  # icon_off_color: "gray"
  # label_on_color: "white"
  # label_off_color: "gray"
  # button_text_color: "white"
  icon_on_color: 0x22C55E
  icon_off_color: 0xEF4444
  icon_temp_color: 0xF59E0B
  icon_temp_target_color: 0xEE0000
  icon_humidity_color: 0x38BDF8

  bg_color: 0x1E293B
  border_color: 0x334155

  label_title_color: 0xF8FAFC
  label_on_color: 0xF8FAFC
  label_description_color: 0xCBD5E1
  label_spinbtn_color: 0x0F172A

  # LCD back light modes - Code in backlight_time.yaml
  # Set Day mode - starts at Sunrise - screen at 100%
  touchscreen_daytime_brightness: "100%"
  # Set Evening mode -  starts at Sunset - screen at 50% (may need to be brighter for some screens)
  touchscreen_nighttime_brightness: "50%"
  # Set Night mode start time (default is midnight)
  touchscreen_night_hour: "0"      # Hour for night mode (0-23)
  touchscreen_night_minute: "0"    # Minute for night mode (0-59)
  # Set touchscreen idle timeout - In night mode back light goes off after this amount of time
  touchscreen_idle_timeout: "60s"

  # Screen Size
  screen_height: 320
  screen_width: 480


# ESPHome configuration specific to REAL DEVICE (not SDL)

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waveshare-ESP32-S3-3.5B Fallback"
    password: !secret wifi_ap_password

captive_portal:

esphome:
  name: "waveshare-esp32-s3-touch-v2"
  friendly_name: "Waveshare ESP32-S3-Touch-LCD-3.5B"
  comment: "Waveshare ESP32-S3-Touch-LCD-3.5B 480px * 320px Smart Screen"

logger:

packages:
  # Packages edited from the great
  #    https://github.com/agillis/esphome-modular-lvgl-buttons
  # project:

  # 1000s of glyphs
  glyphs: !include include/mdi_glyph_substitutions.yaml
  # Some basic sensors
  base_sensors: !include include/sensors_base.yaml
  # Styles + Themes
  theme_style: !include include/theme_style.yaml
  # Backlight control with screen saver
  backlight: !include include/backlight.yaml
  # Hardware description file
  hardware: !include include/hw_waveshare-esp32-s3-touch-lcd-3.5b.yaml

  # MAIN UI DESIGN
  # The core part of this project:
  font: !include include/font.yaml
  images: !include include/images.yaml
  scripts: !include include/scripts.yaml
  ui_design: !include include/lvgl_page_main.yaml
  heating_sensors: !include include/sensors.yaml
  api: !include include/api.yaml
