sensor:
  # CURRENT TARGET TEMPERATURE 
  - platform: homeassistant
    id: sensor_temp_target_now
    entity_id: ${ha_temperature_sensor_id}
    on_value:
      # update target temperature on the "Heating" tab ROW
      - lvgl.label.update:
          id: lbl_current_target_temperature
          text: !lambda |-
            char buf[32];
            sprintf(buf, "%.1f°C", x);
            return std::string(buf);
      - lvgl.label.update:
          id: lbl_current_target_temperature_icon
          text: !lambda |-
            float diff = x - id(sensor_temp_${temp_setting1_id}).state;
            if (diff < 0) {
              diff = -diff;
            }
            if (diff < 0.01f) {
              return "${mdi_sun_thermometer}";
            }
            return "${mdi_coolant_temperature}";

      # update target temperature on the "Heating" tab,
      # inside the box dedicated to each room
      - lambda: |-
          lv_obj_t *room_labels[] = {
            id(lbl_target_temp_heating_${room1_id}),
            id(lbl_target_temp_heating_${room2_id}),
            id(lbl_target_temp_heating_${room3_id}),
            nullptr,
          };
          if (to_string(${num_rooms}) == "4") {
            room_labels[3] = id(lbl_target_temp_heating_${room4_id});
          }

          char buf[32];
          snprintf(buf, sizeof(buf), "%.1f°C", x);
          for (auto *label : room_labels) {
            if (label != nullptr) {
              lv_label_set_text(label, buf);
            }
          }

      - logger.log:
          format: "Updated current target temperature to value %f"
          args: [ 'id(sensor_temp_target_now).state' ]
