# File: sensors_basic_esp32.yaml
# Purpose: Declares some sensors that are only relevant to ESP32-based devices (not SDL target)
# List of subtitutions:
#   - none

---
button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    internal: true
    
  - platform: internal_temperature
    id: cpu_temperature
    name: "CPU Temperature"
    #unit_of_measurement: "°C"
    icon: mdi:thermometer
    entity_category: diagnostic    

  # Reports the WiFi signal strength in %
  - platform: copy
    id: wifi_signal_db_percent
    source_id: wifi_signal_db
    name: "WiFi Strength"
    icon: mdi:wifi
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
      - throttle: 60s
    unit_of_measurement: "%"
    device_class: ""
    entity_category: diagnostic
    on_value:
        then:
          - lvgl.label.update:
              id: lbl_wifi_signal_db_percent
              text:
                format: "%.0f%%"
                args: [ 'id(wifi_signal_db_percent).state' ]

text_sensor:
  - platform: wifi_info
    mac_address:
      id: mac_address
      name: "MAC Address"
      icon: mdi:network-pos
      entity_category: diagnostic
      on_value:
          - lvgl.label.update:
              id: lbl_connected_mac
              text:
                format: "%s"
                args: [ 'id(mac_address).state.c_str()' ]

    ip_address:
      id: ip_address
      name: "IP Address"
      icon: mdi:ip-network
      entity_category: diagnostic
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_ip_address
              text:
                format: "%s"
                args: [ 'id(ip_address).state.c_str()' ]
          - lvgl.qrcode.update:
              id: qrcode_ip_address
              text:
                format: "http://%s"
                args: [ 'id(ip_address).state.c_str()' ]
          - logger.log:
              format: "Updated QRcode for IP address of this device to point to http://%s"
              args: [ 'id(ip_address).state.c_str()' ]

    ssid:
      id: connected_ssid
      name: "Connected SSID"
      icon: mdi:wifi-check
      entity_category: diagnostic
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_connected_ssid
              text:
                format: "%s"
                args: [ 'id(connected_ssid).state.c_str()' ]
