name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ main ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ main ]

permissions:
  # required in case of tags to update releases
  contents: write

jobs:
  # see https://github.com/esphome/esphome-project-template/tree/main/.github/workflows
  build:
    name: Build ESPHome project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: Create dummy secrets.yaml
        run: |
          cat > secrets.yaml << 'EOF'
          wifi_ssid: "dummy-ssid"
          wifi_password: "dummy-password"
          wifi_ap_password: "dummy-ap-password"
          latitude: 0.0
          longitude: 0.0
          encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
          ota_password: "00000000000000000000000000000000"
          ha_long_lived_token: "Bearer dummy-token"
          EOF
      - name: ESPHome
        uses: esphome/build-action@v7
        with:
          yaml-file: example-instance.yaml
          version: stable
      - name: Upload files to release
        uses: softprops/action-gh-release@v2.4.2
        if: github.ref_type == 'tag'
        with:
          files: |
            */*.ota.bin
            */*.factory.bin
